# Generated by Django 3.0.6 on 2020-05-27 21:55

import datetime
from django.db import migrations, models
import projectsApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('descricao', models.TextField(blank=True, max_length=4096, null=True)),
                ('sigla', models.CharField(blank=True, max_length=500, null=True)),
                ('inicio', models.DateField(default=datetime.date.today)),
                ('termino', models.DateField(blank=True, null=True)),
                ('agencia', models.CharField(blank=True, max_length=500, null=True)),
                ('programa', models.CharField(blank=True, max_length=500, null=True)),
                ('natureza', models.CharField(blank=True, max_length=500, null=True)),
                ('situacao', models.CharField(blank=True, max_length=500, null=True)),
                ('processo', models.CharField(blank=True, max_length=500, null=True)),
                ('resolucao', models.CharField(blank=True, max_length=500, null=True)),
                ('imagem_divulgacao', models.ImageField(blank=True, null=True, upload_to=projectsApp.models.path_and_rename_projeto)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoIntegrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
