version: "3"
services:
  app:
    container_name: intranet
    restart: always
    build: . # Current directory!
    command: > 
        bash -c "
            while ! nc -z db 3306; do
                echo 'App waiting for database...';
                sleep 1;
            done;
            python3 application/manage.py runserver 0.0.0.0:8603
        "
    volumes:
      - .:/code
    ports:
      - "8603:8603"
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:latest
    container_name: mysql-intranet
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret123
      - MYSQL_DATABASE=intranet_app
      - MYSQL_USER=intranet_app
      - MYSQL_PASSWORD=intranet_app123

