# Generated by Django 3.0.7 on 2020-06-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='estrangeiro',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
